#pragma once

#define GIT2CPP_VERSION_MAJOR 0
#define GIT2CPP_VERSION_MINOR 0
#define GIT2CPP_VERSION_PATCH 2

// e.g. ".rc0"
#define GIT2CPP_VERSION_SUFFIX

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)
#define GIT2CPP_VERSION_STRING (STR(GIT2CPP_VERSION_MAJOR) "." STR(GIT2CPP_VERSION_MINOR) "." STR(GIT2CPP_VERSION_PATCH) GIT2CPP_VERSION_SUFFIX)
